name: GCond
channels:
- pytorch 
- conda-forge
- fragcolor
- anaconda
- defaults
dependencies:
- pytorch==1.7.0
- pip:
  - torch_geometric==1.6.3
  - scipy==1.6.2
  - numpy==1.19.2
  - ogb==1.3.0
  - tqdm==4.59.0
  - torch_sparse==0.6.9
  - torchvision==0.8.0
  - configs==3.0.3
  - deeprobust==0.2.4
  - scikit_learn==1.0.2
  - torch_scatter

  pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu110.html
