name: MY
channels:
- pytorch 
- dglteam
- conda-forge
- fragcolor
- anaconda
- defaults
dependencies:
- cuda10.0
- cudatoolkit=10.2
- cudnn=7.6.5
- python=3.7
- torchvision
- pip:
  - pyyaml==5.4.1
  - tqdm
  - tensorboardX
  - scikit-learn
  - ogb
  - torch-geometric
  - torch_sparse
  - torch-scatter
  - dgl-cu102
  - torch==1.9.0
  - scipy==1.6.2
  - numpy==1.19.2
  - deeprobust==0.2.4

  pip install --no-index torch-scatter torch_sparse  -f https://pytorch-geometric.com/whl/torch-1.9.0%2Bcu102.html

